### ISSUE TITLE
GBMLGG dataset

### ISSUE THREAD

**Issue by franzt7788** [Innse/MOTCat#10]
Hi @Innse , I am curious about how to get the GBMLGG dataset? I didn't find a specific GMBLGG dataset in the TCGA website and didn't see any notes about how to download it. Could you give me some hints about it? Thank you.

**Comment by Innse** [comment]
Hi, it consists of GBM and LGG dataset in TCGA. Just combine them.

**Comment by franzt7788** [comment]
> Hi, it consists of GBM and LGG dataset in TCGA. Just combine them.

I got it. Thank you!
