### ISSUE TITLE
Duplicate files name of same patient

### ISSUE THREAD

**Issue by JIaqiYang78** [Innse/MOTCat#11]
Hi author, 

I want to ask where in your codes solved the problem of duplicate files name under a same patient. For example, here are several wsi feature files for one patient under a same case ID. So, where did you solve this problem in your dataset load codes? Thank you in advance!

**Comment by Innse** [comment]
Hi. Just concat them together, which can be found in https://github.com/Innse/MOTCat/blob/e5ae896e1c333d6275db26d2ec2f971b8a2a26b1/dataset/dataset_survival.py#L300C29-L300C68
