### ISSUE TITLE
c-index evaluation question

### ISSUE THREAD

**Issue by Reshiramss** [Innse/MOTCat#12]
Thank you very much for your work. I would like to ask why I encountered a situation where the final c-index evaluation metric is stuck at 0.5000 when I am modifying the model. Could you please explain why this is happening?

**Comment by Innse** [comment]
I guess your model failed to converge, as 0.5 of C-Index means a random guess. Can you provide more details to help figure out what happened? e.g., what did you modify?

**Comment by Reshiramss** [comment]
Thank you very much for your reply. I am trying to reproduce the results of survival analysis prediction using transmil mentioned in your paper on luad. Could you please provide this part of the content?

**Comment by Innse** [comment]
Sure. What details would you like to know?

**Comment by Reshiramss** [comment]
Thank you for your response. Could you please provide this part of the code?

**Comment by Innse** [comment]
Since this repository is meant to provide the code of MOTCat, I won't upload this part of the code. But if you need it, please email me.

**Comment by Reshiramss** [comment]
Thank you very much for your response. I truly appreciate your assistance. If I could obtain the code, it would be of immense help to me.

在 2024-06-09 15:38:50，YX_Xu ***@***.***> 写道：


Since this repository is meant to provide the code of MOTCat, I won't upload this part of the code. But if you need it, please email me.
