### ISSUE TITLE
Can you make the project's code open-source in the near future? 

### ISSUE THREAD

**Issue by Spason** [Innse/MOTCat#2]
I recently had the opportunity to read your article, and I must say that I was highly impressed with both the descriptions and the experimental results presented. Your work has sparked a great deal of interest in me.
With regards to your project, I wanted to inquire about the availability of the code. I am keen on exploring and understanding the implementation details further, and having access to the code would greatly facilitate this process. I was wondering if you have plans to make the project's code open-source in the near future? 
Thank you for considering my request, and I'm looking forward to your response.

**Comment by Innse** [comment]
@Spason The code is released.
