### ISSUE TITLE
Being stuck at "runing with mcat coattn" when running the MCAT model.

### ISSUE THREAD

**Issue by Spason** [Innse/MOTCat#3]
Hello, thank you for the excellent work you have completed and for providing the code. I wonder if you have ever encountered the issue of being stuck at "runing with mcat coattn" when running the MCAT model. This problem usually occurs during the training of the second fold. If you have experienced this issue before, I would appreciate your guidance on how to resolve it. Thank you in advance for your response.

**Comment by Spason** [comment]
> Hello, thank you for the excellent work you have completed and for providing the code. I wonder if you have ever encountered the issue of being stuck at "runing with mcat coattn" when running the MCAT model. This problem usually occurs during the training of the second fold. If you have experienced this issue before, I would appreciate your guidance on how to resolve it. Thank you in advance for your response.

Additionally, I have also encountered the same issue when running the MCAT project.

**Comment by Innse** [comment]
Yes. We reproduced the same issue when running with MCAT. And we found that it is not specific to the second fold, but every time one fold is finished. We currently haven't figured out why this happened. One solution to this problem is to train MCAT fold by fold manually.

**Comment by Spason** [comment]
It's a super wise way to solve. So nice to receive your response, thank you very much!

**Comment by Spason** [comment]
> Yes. We reproduced the same issue when running with MCAT. And we found that it is not specific to the second fold, but every time one fold is finished. We currently haven't figured out why this happened. One solution to this problem is to train MCAT fold by fold manually.

 It's a super wise way to solve. So nice to receive your response, thank you very much!
