### ISSUE TITLE
Problems in the processing of WSI dataset

### ISSUE THREAD

**Issue by BusyJzy599** [Innse/MOTCat#5]
I am using the histolab library to process the downloaded WSI dataset. The otsu threshold was followed to cut out patches containing greater than or equal to 50% of the tissue area (w/o overlap). However, during the course of the experiment it was found that the resultant metrics were not as expected. After checking, I believe it is a problem with my dataset processing code or paradigm, but due to local resource constraints there is no way to make multiple attempts. **I hope to borrow the processing code from your work, and I would be more grateful if you can provide me with the feature files that have been extracted!** Looking forward to your reply.

**Comment by Innse** [comment]
We directly used the code of CLAM to process WSI and extracted features with the default settings. Please refer to https://github.com/mahmoodlab/CLAM .
