### ISSUE TITLE
TCGA上数据集的可用病例数量不同？以及WSI的下载问题

### ISSUE THREAD

**Issue by chenxinli001** [Innse/MOTCat#6]
![image](https://github.com/Innse/MOTCat/assets/58136000/fb5493df-13fc-4c82-ad6b-fb0b5d8ddacb)
![image](https://github.com/Innse/MOTCat/assets/58136000/55a9fffe-dad2-4035-ac69-1c518034d837)

Q1) 上面的是本文的数据集case, 下面是MCAT的，请问为什么会出现case数量不一致的情况呢？包括现在看TCGA，BLCA的case数量是412；如何解决这个不一致性？

Q2) 下载WSI的时候, 是选tissue slide or diagnostic slide or both?
![Uploading image.png…]()

**Comment by chenxinli001** [comment]
![image](https://github.com/Innse/MOTCat/assets/58136000/f20d079d-a87c-44a7-ae43-164a76aa2e1e)
Q2) 下载WSI的时候, 是选tissue slide or diagnostic slide or both?

**Comment by Innse** [comment]
Q1) 我们不清楚MCAT的case数量是什么情况，我只能陈述我所使用的数据情况。例如BLCA，我们能从TCGA获得的case数量只有386 cases（应使用diagnostic），然后去掉tissue占比太小的case（用CLAM的默认设置），有基因数据配对的cases只有这么多

Q2) 应使用diagnostic slide

**Comment by Innse** [comment]
> Q1) 我们不清楚MCAT的case数量是什么情况，我只能陈述我所使用的数据情况。例如BLCA，我们能从TCGA获得的case数量只有386 cases（应使用diagnostic），然后去掉tissue占比太小的case（用CLAM的默认设置），有基因数据配对的cases只有这么多
> 
> Q2) 应使用diagnostic slide

还去除了一些没有survival标签的cases

**Comment by chenxinli001** [comment]
![image](https://github.com/Innse/MOTCat/assets/58136000/662092cb-b5ee-4c59-947f-d9fb5b384a7f)
你好，大概全部数据集的slides加起来得有四五个T.... 这个scale是对的吧？

**Comment by Innse** [comment]
> ![image](https://private-user-images.githubusercontent.com/58136000/285011447-662092cb-b5ee-4c59-947f-d9fb5b384a7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4Njc4NjAsIm5iZiI6MTcwMTg2NzU2MCwicGF0aCI6Ii81ODEzNjAwMC8yODUwMTE0NDctNjYyMDkyY2ItYjVlZS00YzU5LTk0N2YtZDlmYjViMzg0YTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDEyNTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3Mzc5ZDVlZjM0ODAyMGNiYjc3OGVjMjlkMDc0Nzg2ZDY5NzRjMWM3Mzk0N2MzNTNlMTU4YTk4MTk5MWIyMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aU2baR88O0CHvCkHWFRtQzvWnVvwZiq7HgXsutpCRDM) 你好，大概全部数据集的slides加起来得有四五个T.... 这个scale是对的吧？

差不多，因为一张WSI大概1个G左右。
