### ISSUE TITLE
What script is used in CLAM? How big of a GPU is needed to run MOTCat?

### ISSUE THREAD

**Issue by lichencan** [Innse/MOTCat#7]
"Use the WSI processing tool provided by [CLAM](https://github.com/mahmoodlab/CLAM) to extract resnet-50 pretrained 1024-dim feature for each 256 
 256 patch (20x), which we then save as .pt files for each WSI. So, we get one pt_files folder storing .pt files for all WSIs of one study."
use：python create_patches_fp.py --source DATA_DIRECTORY --save_dir RESULTS_DIRECTORY --patch_size 256 --preset tcga.csv --seg --patch --stitch
and python create_patches_fp.py --source DATA_DIRECTORY --save_dir RESULTS_DIRECTORY --patch_size 256 --seg --process_list process_list_edited.csv
Thank you very much for your project, and I look forward to your reply.

**Comment by Innse** [comment]
Hi. First, features of patches with a size of 512x512 are extracted at level 0 using CLAM. These features are then resized to 256x256, resulting in 20x features.
Regarding GPU, MOTCat typically requires a GPU with a memory capacity of less than 1,000MB, making it compatible with most GPUs available today.
