### ISSUE TITLE
Nan values in the extracted feature

### ISSUE THREAD

**Issue by wzhang-home** [Innse/MOTCat#8]
Hi there,

Thank you for sharing your nice work!
I met a problem when I try to train your model, it returned the nan loss and risk like below:
_batch 99, loss: nan, label: 1, event_time: 14.6800, risk: nan_

The error info are:
  _File "/opt/anaconda3/envs/ct/lib/python3.7/site-packages/sksurv/metrics.py", line 223, in concordance_index_censored
    event_indicator, event_time, estimate)
  File "/opt/anaconda3/envs/ct/lib/python3.7/site-packages/sksurv/metrics.py", line 49, in _check_inputs
    estimate = _check_estimate_1d(estimate, event_time)
  File "/opt/anaconda3/envs/ct/lib/python3.7/site-packages/sksurv/metrics.py", line 36, in _check_estimate_1d
    estimate = check_array(estimate, ensure_2d=False)
  File "/opt/anaconda3/envs/ct/lib/python3.7/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/opt/anaconda3/envs/ct/lib/python3.7/site-packages/sklearn/utils/validation.py", line 116, in _assert_all_finite
    type_err, msg_dtype if msg_dtype is not None else X.dtype
ValueError: Input contains NaN, infinity or a value too large for dtype('float64')._

I checked the input and output of the model and found there are many nan values in the feature of both WSI and omic data which lead to the nan output of the hazards and S.  I strictly followed the instructions you provided and really confused why this nan value would appear. If you met this problem before, could you tell me how to solve this?

Thanks!

**Comment by Innse** [comment]
Sorry, I didn't encounter this problem. Please check your features extracted by CLAM first.

**Comment by wzhang-home** [comment]
> Sorry, I didn't encounter this problem. Please check your features extracted by CLAM first.

Thank you for your reply.  I will look into it.  

Best.
